# SPDX-License-Identifier: Apache-2.0
# tox configuration for the OpenDev/Zuul gate. Mirrors the GHA "unit" job and
# adds a lint env. The functional job runs separately (see zuul.d/jobs.yaml).
[tox]
envlist = py311, pep8
skipsdist = True

[testenv]
usedevelop = False
deps =
    -r{toxinidir}/requirements.txt
    pytest
commands = pytest {toxinidir}/tests -q

[testenv:pep8]
deps = pre-commit
commands = pre-commit run --all-files

[flake8]
max-line-length = 100
extend-ignore = E203, W503
exclude = .git,.tox,meetbot/engine
